[package]
name = "carbonyl"
version = "0.0.3"
edition = "2021"

[dependencies]
libc = "0.2.141"
unicode-width = "0.1.10"
unicode-segmentation = "1.10.1"
chrono = "0.4.24"

[lib]
name = "carbonyl"
path = "src/lib.rs"
crate-type = ["cdylib"]
